language: rust
os: linux
dist: xenial

cache:
  - npm
  - cargo

branches:
  only:
    - master
before_install:
  - rustc --version
  - rustup target add wasm32-unknown-unknown
  - cargo install wasm-pack
  - wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash
  - source ~/.nvm/nvm.sh
  - nvm install 16.13
  - node -v
script:
  - wasm-pack build
  - cd ${TRAVIS_BUILD_DIR}/www
  - npm i --prefer-offline --skip-audit
  - npm run build
deploy:
  provider: pages
  token: "$GH_TOKEN"
  local_dir: dist
  strategy: git
  skip_cleanup: true

